Fix query for array
kant2002/AspNetCore.Helpers pull request #5
Opened 2019-10-01 11:10 UTC by Cmouse87

2019-10-01 11:58 UTC, kant2002 requested changes
Small comment

2019-10-01 11:58 UTC, kant2002 commented on AspNetCore.Helpers.Tests/AspNetCore.Helpers.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Why this change?

2019-10-02 03:45 UTC, Cmouse87 commented on AspNetCore.Helpers.Tests/AspNetCore.Helpers.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
да прогон какой-то был, вроде отменил

2019-10-02 06:13 UTC, kant2002 approved these changes
LGTM

2019-10-02 06:13 UTC, merged